# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWebEngineWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWebEngineWidgets import *
from PyQt5.QtCore import *
import os
from mapgen import generate_map
import sqlite3

#coor = [[21.7723, 41.7165], [22.50217, 41.14762]]

class Line2(QtWidgets.QLineEdit):
    def keyPressEvent(self, event):
        if event.key() in (Qt.Key_Return, Qt.Key_Enter):
            #QMessageBox.question(self, 'Link', final, QMessageBox.Ok, QMessageBox.Ok)
            #self.parent().parent().close()
            self.parent().children()[6].setText("Toll price for toll route: 40den\nLength in km of toll route: 54.6km\nLength in km of toll-less route: 53.6km\nDifference in length: 1km in favor of toll-less\nTime needed for toll route: 47min\nTime needed for toll-less route: 1hr 15min\nDifference in time: 28min\nGas price for toll route: 325.416den\nGas price for toll-less route: 319.456den\nDifference in total price: 45.96 den in favor of toll-less route")
            self.parent().children()[10].setText("Toll-less route\nReasoning: The toll-less route is simply shorter and cheaper.")
            #print(self.parent().children())
            #for child in self.parent().children():
            #    print(child.objectName())
            file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "map.html"))
            local_url = QUrl.fromLocalFile(file_path)
            conn = sqlite3.connect("baza.db")
            command = ("select lat from gradovi where ime like \""+self.parent().children()[3].text()+"\";")
            startlat = conn.execute(command).fetchall()[0][0]
            command = ("select lon from gradovi where ime like \""+self.parent().children()[3].text()+"\";")
            startlon = conn.execute(command).fetchall()[0][0]
            command = ("select lat from gradovi where ime like \""+self.text()+"\";")
            destlat = conn.execute(command).fetchall()[0][0]
            command = ("select lon from gradovi where ime like \""+self.text()+"\";")
            deslon = conn.execute(command).fetchall()[0][0]
            conn.close()
            coor = [[startlon,startlat],[deslon,destlat]]
            generate_map(coor)
            self.parent().children()[1].load(local_url)
            self.parent().children()[1].show()
            return
        else:
            super().keyPressEvent(event)
        #super().keyPressEvent(event)
    #def mousePressEvent(self, a0: QtGui.QMouseEvent):
    #    QMessageBox.question(self, 'Link', 'Text', QMessageBox.Ok, QMessageBox.Cancel)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 470)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 10, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 0, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = Line2(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(540, 10, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 90, 351, 181))
        self.textBrowser.setOverwriteMode(False)
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 50, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(410, 90, 351, 321))
        self.graphicsView.setObjectName("graphicsView")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 300, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 350, 351, 61))
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.webwidget = QWebEngineView(self.centralwidget)
        self.webwidget.setGeometry(QtCore.QRect(410, 90, 351, 321))
        self.webwidget.setObjectName("webwidget")

        '''self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(410, 90, 351, 321))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 349, 319))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 641, 401))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/images/map.png"))
        self.label_6.setObjectName("label_6")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(331, 0, 20, 321))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(0, 301, 331, 20))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.graphicsView.raise_()'''
        self.webwidget.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.label_2.raise_()
        self.lineEdit_2.raise_()
        self.textBrowser.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.textBrowser_2.raise_()
        #self.scrollArea.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFIle.addAction(self.actionOpen)
        self.menuFIle.addAction(self.actionSave)
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.actionExit)
        self.menubar.addAction(self.menuFIle.menuAction())

        #Later-Defined
        def actExit():
            MainWindow.close()
        self.actionExit.triggered.connect(actExit)
        #-------------

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Starting point:"))
        self.label_2.setText(_translate("MainWindow", "Destination:"))
        self.textBrowser.setPlaceholderText(_translate("MainWindow", "Toll price for toll route:\nLength in km of toll route:\nLength in km of toll-less route:\nDifference in length:\nTime needed for toll route:\nTime needed for toll-less route:\nDifference in time:\nGas price for toll route:\nGas price for toll-less route:\nDifference in total price:"))
        self.label_3.setText(_translate("MainWindow", "Stats:"))
        self.label_4.setText(_translate("MainWindow", "Map:"))
        self.label_5.setText(_translate("MainWindow", "Estimated superior route:"))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
